"""build_graph(): native LangGraph wiring for support_pipeline.

This is ordinary LangGraph. The functions it wires carry lg2m @node / @predicate
annotations (see nodes.py and predicates.py) and the conditional fan-out comes
from the generated `route_after_classify` (see routing.py), but the wiring here
is plain: you still call add_node / add_edge / add_conditional_edges yourself.
The add_node names must match the @node ids; lg2m cross-checks them against the
diagram.

Three boundaries lg2m cannot infer from get_graph() are declared here so they
become introspectable:
  - the Command(goto) edge out of escalate_to_human, via destinations=,
  - the Send fan-out out of map_items, via the conditional edge to process_item,
  - the investigate subgraph, flattened when lg2m reads get_graph(xray=True).

lg2m's entry point (lg2m.toml) is `support_pipeline.graph:build_graph`. lg2m calls
this, reads `compiled.get_graph()` for the real topology, and then reconciles that
topology with the @node / @predicate / lg2m.router annotations and the diagram.
"""

from langgraph.graph import END, START, StateGraph

from .nodes import (
    analyze,
    auto_resolve,
    classify_intent,
    compose_reply,
    escalate_to_human,
    fetch_history,
    gather_logs,
    ingest_ticket,
    lookup_account,
    map_items,
    process_item,
    reduce_items,
)
from .routing import fan_out_items, route_after_classify
from .state import PipelineState


def build_investigate_subgraph():
    sub = StateGraph(PipelineState)
    sub.add_node("gather_logs", gather_logs)
    sub.add_node("analyze", analyze)
    sub.add_edge(START, "gather_logs")
    sub.add_edge("gather_logs", "analyze")
    sub.add_edge("analyze", END)
    return sub.compile()


def build_graph():
    graph = StateGraph(PipelineState)

    graph.add_node("ingest_ticket", ingest_ticket)
    graph.add_node("fetch_history", fetch_history)
    graph.add_node("lookup_account", lookup_account)
    graph.add_node("classify_intent", classify_intent)
    graph.add_node("auto_resolve", auto_resolve)
    # Command node: declare destinations so the goto edge is introspectable.
    graph.add_node("escalate_to_human", escalate_to_human,
                   destinations=("compose_reply",))
    graph.add_node("investigate", build_investigate_subgraph())   # subgraph as a node
    graph.add_node("map_items", map_items)
    graph.add_node("process_item", process_item)
    graph.add_node("reduce_items", reduce_items)
    graph.add_node("compose_reply", compose_reply)

    # chain in
    graph.add_edge(START, "ingest_ticket")

    # parallel fork: ingest -> {fetch_history, lookup_account}
    graph.add_edge("ingest_ticket", "fetch_history")
    graph.add_edge("ingest_ticket", "lookup_account")
    # parallel fan-in (join): both -> classify_intent (runs once, after both)
    graph.add_edge("fetch_history", "classify_intent")
    graph.add_edge("lookup_account", "classify_intent")

    # conditional fan-out; route_after_classify is generated by lg2m.router from
    # the mapping in routing.py, and it owns the path_map (keyed by predicate name),
    # so the runtime targets and the diagram labels cannot drift from the mapping.
    graph.add_conditional_edges(
        "classify_intent",
        route_after_classify,
        route_after_classify.path_map,
    )

    # subgraph -> map_items -> (Send) process_item -> reduce_items -> compose
    graph.add_edge("investigate", "map_items")
    graph.add_conditional_edges("map_items", fan_out_items, ["process_item"])
    graph.add_edge("process_item", "reduce_items")
    graph.add_edge("reduce_items", "compose_reply")

    # the auto_resolve branch converges on compose_reply
    graph.add_edge("auto_resolve", "compose_reply")
    # escalate_to_human reaches compose_reply via Command(goto), not an edge.

    graph.add_edge("compose_reply", END)

    return graph.compile()
