"""Generate an annotated LangGraph package from a doc-side ``GraphModel``
(docs/design.md Section 10).

``gen --from-doc`` reads the Markdown contract, assembles a canonical
``GraphModel(origin="markdown")``, and this module turns that into the source text of an
annotated Python package: ``state.py`` (``@state_model`` / ``@data_model`` classes),
``nodes.py`` (``@node`` stubs), ``predicates.py`` (``@predicate`` stubs), ``routing.py``
(``lg2m.router(...)`` mappings), ``graph.py`` (a complete ``build_graph()``), and
``__init__.py``.

This is **pure string codegen and imports no framework**. The *generated* code imports
LangGraph (it is the user's graph), but this emitter never does. Generation is LangGraph-only
for v1; ``--framework langchain`` raises :class:`ScaffoldError`. Subgraph / ``Send`` / ``Command``
sugar is not reconstructed from the flattened canonical model (a documented v1 limitation): the
emitter renders flattened ``parent:child`` ids best-effort and leaves a ``# TODO`` for any
conditional edge without a router mapping.
"""

from __future__ import annotations

import keyword

from lg2m.diff.assemble import END_ID, START_ID
from lg2m.ir import GraphModel, Node, NodeKind, Route

SUPPORTED_FRAMEWORKS = ("langgraph",)
SUPPORTED_MODEL_STYLES = ("typeddict", "pydantic")

GENERATED_FILES = ("__init__.py", "state.py", "nodes.py", "predicates.py", "routing.py", "graph.py")


class ScaffoldError(Exception):
    """Generation cannot proceed: a bad option or a contract missing its state model."""


def generate_code(
    model: GraphModel,
    *,
    framework: str = "langgraph",
    model_style: str = "typeddict",
) -> dict[str, str]:
    """Render ``model`` into ``{filename: source}`` for an annotated LangGraph package.

    Raises :class:`ScaffoldError` for an unsupported ``framework`` / ``model_style`` or a
    contract with no ``@state_model``.
    """
    if framework == "langchain":
        raise ScaffoldError(
            "--framework langchain is not yet supported; v1 emits LangGraph only"
        )
    if framework not in SUPPORTED_FRAMEWORKS:
        raise ScaffoldError(
            f"unknown framework {framework!r}; supported: {', '.join(SUPPORTED_FRAMEWORKS)}"
        )
    if model_style not in SUPPORTED_MODEL_STYLES:
        raise ScaffoldError(
            f"unknown model-style {model_style!r}; supported: {', '.join(SUPPORTED_MODEL_STYLES)}"
        )
    if not model.state_model_name:
        raise ScaffoldError("the contract declares no @state_model; cannot build a StateGraph")

    return {
        "__init__.py": _emit_init(),
        "state.py": _emit_state(model, model_style),
        "nodes.py": _emit_nodes(model),
        "predicates.py": _emit_predicates(model),
        "routing.py": _emit_routing(model),
        "graph.py": _emit_graph(model),
    }


# --- identifiers -------------------------------------------------------------


def _ident(raw: str) -> str:
    """A valid identifier from a node/route id (``parent:child`` -> ``parent_child``)."""
    out = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in raw)
    if not out or out[0].isdigit():
        out = "_" + out
    if keyword.iskeyword(out):
        out += "_"
    return out


def _real_nodes(model: GraphModel) -> list[Node]:
    return [n for n in model.nodes.values() if n.kind is NodeKind.NODE]


def _predicate_names(model: GraphModel) -> list[str]:
    """Every predicate referenced by a route (in branch order), then any extra documented ones."""
    names: list[str] = []
    for route in model.routes.values():
        for pred, _target in route.branches:
            if pred not in names:
                names.append(pred)
    for name in model.predicates:
        if name not in names:
            names.append(name)
    return names


# --- per-file emitters -------------------------------------------------------


def _emit_init() -> str:
    return (
        '"""Generated by ``lg2m gen --from-doc``. Fill in the node and predicate bodies."""\n\n'
        "from .graph import build_graph\n\n"
        '__all__ = ["build_graph"]\n'
    )


def _emit_state(model: GraphModel, model_style: str) -> str:
    base = "TypedDict" if model_style == "typeddict" else "BaseModel"

    reducers: list[str] = []
    for dm in model.models.values():
        for attr in dm.attributes:
            if attr.reducer and attr.reducer not in reducers:
                reducers.append(attr.reducer)

    typing_names = ["Annotated"] if reducers else []
    if model_style == "typeddict":
        typing_names.append("TypedDict")

    stub_reducers = [r for r in reducers if r != "add_messages" and not r.startswith("operator.")]
    decorators = sorted(
        {("state_model" if dm.is_graph_state else "data_model") for dm in model.models.values()}
    )

    lines = [
        '"""Generated state and data models (``lg2m gen --from-doc``)."""',
        "",
        "from __future__ import annotations",
        "",
    ]
    if typing_names:
        lines.append(f"from typing import {', '.join(sorted(typing_names))}")
    if any(r.startswith("operator.") for r in reducers):
        lines.append("import operator")
    if "add_messages" in reducers:
        lines.append("from langgraph.graph.message import add_messages")
    if model_style == "pydantic":
        lines.append("from pydantic import BaseModel")
    lines.append(f"from lg2m import {', '.join(decorators)}")
    lines.append("")

    for reducer in stub_reducers:
        lines += [
            "",
            f"def {_ident(reducer)}(left, right):",
            f'    raise NotImplementedError("TODO: implement reducer {reducer!r}")',
            "",
        ]

    for dm in model.models.values():
        lines.append("")
        lines.append("@state_model" if dm.is_graph_state else "@data_model")
        lines.append(f"class {dm.name}({base}):")
        if not dm.attributes:
            lines.append("    pass")
        for attr in dm.attributes:
            if attr.reducer:
                lines.append(f"    {attr.name}: Annotated[{attr.type_str}, {attr.reducer}]")
            else:
                lines.append(f"    {attr.name}: {attr.type_str}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def _emit_nodes(model: GraphModel) -> str:
    lines = [
        '"""Generated node stubs (``lg2m gen --from-doc``)."""',
        "",
        "from lg2m import node",
        "",
    ]
    for node in _real_nodes(model):
        lines += [
            "",
            f'@node("{node.id}")',
            f"def {_ident(node.id)}(state):",
            f'    raise NotImplementedError("TODO: implement node {node.id!r}")',
            "",
        ]
    return "\n".join(lines).rstrip("\n") + "\n"


def _emit_predicates(model: GraphModel) -> str:
    lines = [
        '"""Generated predicate stubs (``lg2m gen --from-doc``)."""',
        "",
        "from lg2m import predicate",
        "",
    ]
    for name in _predicate_names(model):
        lines += [
            "",
            f'@predicate("{name}")',
            f"def {_ident(name)}(state) -> bool:",
            f'    raise NotImplementedError("TODO: implement predicate {name!r}")',
            "",
        ]
    return "\n".join(lines).rstrip("\n") + "\n"


def _emit_routing(model: GraphModel) -> str:
    lines = [
        '"""Generated routers (``lg2m gen --from-doc``). Each owns its path_map."""',
        "",
        "import lg2m",
        "",
    ]
    for route in model.routes.values():
        lines.append("")
        lines.append(f'{_route_var(route)} = lg2m.router("{route.source_id}", [')
        for pred, target in route.branches:
            lines.append(f'    ("{pred}", "{target}"),')
        lines.append(f'    (lg2m.ELSE, "{route.else_target}"),')
        lines.append("])")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _emit_graph(model: GraphModel) -> str:
    state_name = model.state_model_name
    nodes = _real_nodes(model)
    node_funcs = sorted({_ident(n.id) for n in nodes})
    route_sources = set(model.routes)

    lines = [
        '"""Generated ``build_graph()`` (``lg2m gen --from-doc``)."""',
        "",
        "from langgraph.graph import END, START, StateGraph",
        "",
    ]
    lines += _import_block(".nodes", node_funcs)
    route_vars = [_route_var(r) for r in model.routes.values()]
    if route_vars:
        lines += _import_block(".routing", route_vars)
    lines.append(f"from .state import {state_name}")
    lines += ["", "", "def build_graph():", f"    graph = StateGraph({state_name})", ""]

    for node in nodes:
        lines.append(f'    graph.add_node("{node.id}", {_ident(node.id)})')
    lines.append("")

    for edge in model.edges:
        if edge.conditional:
            continue
        src = "START" if edge.src_id == START_ID else f'"{edge.src_id}"'
        dst = "END" if edge.dst_id == END_ID else f'"{edge.dst_id}"'
        lines.append(f"    graph.add_edge({src}, {dst})")

    for route in model.routes.values():
        var = _route_var(route)
        lines.append(
            f'    graph.add_conditional_edges("{route.source_id}", {var}, {var}.path_map)'
        )

    for edge in model.edges:
        if edge.conditional and edge.src_id not in route_sources:
            lines.append(
                f"    # TODO: conditional edge {edge.src_id} -> {edge.dst_id} "
                "(Send/Command) is not generated by v1"
            )

    lines += ["", "    return graph.compile()", ""]
    return "\n".join(lines).rstrip("\n") + "\n"


# --- helpers -----------------------------------------------------------------


def _route_var(route: Route) -> str:
    return f"route_{_ident(route.source_id)}"


def _import_block(module: str, names: list[str]) -> list[str]:
    if not names:
        return []
    if len(names) == 1:
        return [f"from {module} import {names[0]}"]
    return [f"from {module} import (", *[f"    {name}," for name in names], ")"]


__all__ = ["GENERATED_FILES", "ScaffoldError", "generate_code"]
