"""Emit a Markdown contract skeleton from a code-side ``GraphModel`` (docs/design.md Section 10).

``gen --from-code`` introspects the real compiled graph, assembles a code-side
``GraphModel(origin="code")``, and this module renders it as the Markdown contract: YAML
frontmatter, an ``## Index`` table, a ``## Graph`` block (canonical mermaid), and the
``## Data Models`` / ``## Predicates`` / ``## Nodes`` / ``## Edges`` sections. Prose is emitted as
``TODO`` (no write-back / 3-way merge in v1 -- docs/design.md Section 12). Re-parsing
the result with ``parse_markdown`` + ``assemble_doc_model`` yields a structurally equal IR.

This is framework-free string assembly that reuses the existing emitters (``emit_mermaid`` for
the diagram, ``emit_table`` for every GFM table). **Limitation:** the code-side IR is flattened
topology vocabulary, so a subgraph appears as ``parent:child`` node ids and ``Send`` / ``Command``
appear as plain conditional edges; the emitter renders those best-effort (it does not reconstruct
``<<fork>>`` / ``<<join>>`` / composite states), and a ``:`` in a flattened id does not round-trip
through mermaid (mermaid's label separator). Subgraph-free graphs round-trip exactly.
"""

from __future__ import annotations

from lg2m.diff.assemble import END_ID, START_ID
from lg2m.ir import Edge, GraphModel, NodeKind
from lg2m.parsing import tables
from lg2m.parsing.mermaid import (
    START_END,
    MermaidDiagram,
    MermaidEdge,
    MermaidState,
    emit_mermaid,
)

_TODO_NODE = "TODO: describe this node."
_TODO_PREDICATE = "TODO: describe this predicate."


def generate_markdown(model: GraphModel) -> str:
    """Render ``model`` as a Markdown ``stateDiagram-v2`` contract skeleton."""
    blocks = [
        _frontmatter(model),
        _title(model),
        _index(model),
        _graph(model),
        _data_models(model),
        _predicates(model),
        _nodes(model),
        _edges(model),
    ]
    lines = [line for block in blocks for line in block]
    return "\n".join(lines).rstrip("\n") + "\n"


# --- sections ----------------------------------------------------------------


def _frontmatter(model: GraphModel) -> list[str]:
    return ["---", f"lg2m_graph: {model.graph_id}", "---", ""]


def _title(model: GraphModel) -> list[str]:
    return [
        f"# {model.graph_id}",
        "",
        "Generated by `lg2m gen --from-code`. The diagram and tables are introspected; the "
        "prose is `TODO` for you to fill in.",
        "",
    ]


def _index(model: GraphModel) -> list[str]:
    rows = [{"id": f"`{n.id}`", "type": "node"} for n in _real_nodes(model)]
    rows += [{"id": f"`{name}`", "type": "predicate"} for name in model.predicates]
    if not rows:
        return []
    return ["## Index", "", *tables.emit_table(["id", "type"], rows), ""]


def _graph(model: GraphModel) -> list[str]:
    diagram = MermaidDiagram()
    for node in _real_nodes(model):
        diagram.states[node.id] = MermaidState(id=node.id)
    for edge in model.edges:
        diagram.edges.append(
            MermaidEdge(
                src=_diagram_id(edge.src_id),
                dst=_diagram_id(edge.dst_id),
                predicate=edge.predicate,
                conditional=edge.conditional,
                is_else=edge.is_else,
            )
        )
    return ["## Graph", "", "```mermaid", *emit_mermaid(diagram), "```", ""]


def _data_models(model: GraphModel) -> list[str]:
    if not model.models:
        return []
    out = ["## Data Models", ""]
    for dm in model.models.values():
        marker = "@state_model" if dm.is_graph_state else "@data_model"
        kind = "graph state" if dm.is_graph_state else "payload model"
        out += [f"### `{dm.name}`", "", f"The {kind} (`{marker}`). TODO: describe.", ""]
        rows = [
            {
                "attribute": f"`{attr.name}`",
                "type": f"`{attr.type_str}`",
                "reducer": (f"`{attr.reducer}`" if attr.reducer else "-"),
                "description": (attr.description or "TODO"),
            }
            for attr in dm.attributes
        ]
        if rows:
            out += tables.emit_table(["attribute", "type", "reducer", "description"], rows)
            out.append("")
    return out


def _predicates(model: GraphModel) -> list[str]:
    if not model.predicates:
        return []
    out = ["## Predicates", ""]
    for name in model.predicates:
        out += [f"### `{name}`", "", _TODO_PREDICATE, ""]
    return out


def _nodes(model: GraphModel) -> list[str]:
    real = _real_nodes(model)
    if not real:
        return []
    out = ["## Nodes", ""]
    for node in real:
        out += [f"### `{node.id}`", "", _TODO_NODE, ""]
        if node.meta:
            fence = "; ".join(f"{key}={value}" for key, value in node.meta.items())
            out += [f"<!-- lg2m: {fence} -->", ""]
    return out


def _edges(model: GraphModel) -> list[str]:
    if not model.edges:
        return []
    rows = [
        {
            "from": f"`{_diagram_id(edge.src_id)}`",
            "to": f"`{_diagram_id(edge.dst_id)}`",
            "label": (f"`{edge.predicate}`" if edge.predicate else ""),
            "kind": _edge_kind(edge),
            "notes": "",
        }
        for edge in model.edges
    ]
    return ["## Edges", "", *tables.emit_table(["from", "to", "label", "kind", "notes"], rows), ""]


# --- helpers -----------------------------------------------------------------


def _real_nodes(model: GraphModel) -> list:
    return [n for n in model.nodes.values() if n.kind is NodeKind.NODE]


def _diagram_id(node_id: str) -> str:
    if node_id in (START_ID, END_ID):
        return START_END
    return node_id


def _edge_kind(edge: Edge) -> str:
    if edge.src_id == START_ID:
        return "start"
    if edge.dst_id == END_ID:
        return "end"
    if edge.is_else or edge.conditional:
        return "conditional"
    if edge.parallel:
        return "parallel"
    return "unconditional"


__all__ = ["generate_markdown"]
